apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worker-screenshot
  name: worker-screenshot
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker-screenshot
    spec:
      containers:
      - name: worker-screenshot
        image: quay.io/cloudytimemachine/worker-screenshot:a68c6114a75dcfd91dd6df728a40a1d6afb4560e
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: PRODUCTION
        - name: GCLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: gcloud-bucket
              key: gcloud-project
        - name: GCLOUD_KEYFILE
          value: /var/gcloud/gcloud.json
        - name: BUCKET_NAME
          value: nodeinteractive
        volumeMounts:
        - mountPath: /var/gcloud
          name: gcloud-bucket
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: gcloud-bucket
          secret:
            secretName: gcloud-bucket
---
